---
title: "ReproResearch_assigment2"
author: "Gleb Artamonov"
date: '2018 july'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Processing data
###Reading the data
```{r}
library(data.table)
library(magrittr)
library(ggplot2)
library(knitr)
options(scipen = 100)
#reading and setting as data.table
storm = read.csv("./repdata%2Fdata%2FStormData.csv") %>% setDT
#set names to lower case
names(storm) %<>% tolower()
str(storm)
datecols=grep("date$|time$",names(storm))
summary(storm)
```
Lets look how events labeled.
```{r}
storm$evtype %>% table
```
Well labels are pretty messy lets clean it a little bit
```{r}
#lets have all events in lower case so Flood and flood where counted the same
storm$evtype %<>% as.character() %>% tolower()
storm$evtype %>% table %>% sort
# lets get rid off summary-rows
# then we will substitute any character that is not a charcter,number or dot
# to spaces and finaly we will compress repeated spaces just to single one
storm[,evtype_short:=evtype]
storm2=storm[!grepl("summary",evtype)]
storm2$evtype_short = storm2$evtype %>% gsub("[^[:alnum:].]"," ",.) %>% 
      trimws %>% gsub("\\s+"," ",.) %>% gsub("\\.$","",.) %>% 
      gsub("winds","wind",.) %>% gsub("record|excessive|extreme","",.) %>% 
      gsub("thunderstorms?","tstm",.) %>% gsub("flooding","flood",.) %>% 
      gsub("hail[ .0-9]+$","hail",.) %>%  gsub("\\s?g?\\d+\\s?(mph)?\\.?","",.) %>% 
      gsub("hurricane.*","hurricane",.)%>% trimws
# %>% unique %>% length()
storm2[,23:28,with=F] %>% summary
#we can see that all variables of interest don't have any missing values
#even thoght there are some strange measurements in expenses columns
#lets delete cases where no damage where done
storm2=storm2[fatalities +injuries+propdmg+cropdmg!=0,]
#here we have some strange measuments
storm2$propdmgexp %>% table
storm2$cropdmgexp %>% table
storm2$propdmgexp %<>% tolower()
storm2$cropdmgexp %<>% tolower()
multchar=function(number,char){
     res=ifelse(char=="k",number*10^3,
            ifelse(char=="m", number*10^6,
                  ifelse(char=="b",number*10^9, number)))
      res
}
# if exp not in k,m,b we calculate damage values as they are 
# so 1 "smth that not k,m,b" will be estimated as 1
storm2=storm2[,propdmgval:=multchar(propdmg,propdmgexp)][
              ,cropdmgval:=multchar(cropdmg,cropdmgexp)]

cols=c("fatalities","injuries","propdmgval","cropdmgval")

stormSummary=storm2[,lapply(.SD,sum,na.rm=T),
                    .SDcols=cols,
                    by=evtype_short]
stormSummary[,dmgval:=propdmgval+cropdmgval]
stormSummary=melt(stormSummary,id.vars = c("evtype_short"),
                  measure.vars = c(cols[1:2],"dmgval"))
# kind of bad with sum==0
stormSummary[,share:=value/sum(value,na.rm=T),
             by=variable]
# we still have a lot of different event_types that have rather typos or some 
# additional information
# lets see the share of those dirty/multilable eventtype in overall damage
# volume/value
setorder(stormSummary,variable,share)
stormSummary[,cumsum:=cumsum(share),by=.(variable)]
stormSummary[cumsum>.2 & variable!="dmgval",evtype_short %>% unique()]
stormSummary[,evtype_health:=evtype_short][
      cumsum<=.2 & variable!="dmgval",evtype_health:="other"]
stormSummary[cumsum>.2 & variable=="dmgval",evtype_short %>% unique()]
stormSummary[,evtype_pcdmg:=evtype_short][
      cumsum<=.2 & variable=="dmgval",evtype_pcdmg:="other"]
stormHealth=stormSummary[variable %in% c("fatalities","injuries"),
                         .(value=sum(value,na.rm = T),
                           share=sum(share,na.rm = T)),
                         by=.(variable,evtype_health)]
stormPCDamage=stormSummary[variable %in% c("dmgval"),
                         .(value=sum(value,na.rm = T),
                           share=sum(share,na.rm = T)),
                         by=.(variable,evtype_pcdmg)]
stormHealth[,srt:=ifelse(evtype_health!="other",share,-share)]
stormPCDamage[,srt:=ifelse(evtype_pcdmg!="other",share,-share)]
#setorder(stormSummary,share_fatalities)
ggplot(data=stormHealth,
       aes(x=reorder(evtype_health,srt),y=value)) + 
      geom_bar(stat="sum") + coord_flip() + 
      geom_text(data=stormHealth[evtype_health!="tornado"],
                aes(label=sprintf("%s (%s%%)",value,
                                  round(share,2)*100)),
                color="red",hjust="left")+ 
      geom_text(data=stormHealth[evtype_health=="tornado"],
                aes(label=sprintf("%s (%s%%)",value,
                                  round(share,2)*100)),
                color="white",hjust="right")+
      facet_wrap(.~variable,scales = "free_x")

ggplot(data=stormPCDamage,
       aes(x=reorder(evtype_pcdmg,srt),y=value/10^9)) + 
      geom_bar(stat="sum") + coord_flip() +
            geom_text(data=stormPCDamage[evtype_pcdmg!="flood"],
                aes(label=sprintf("%s bn$ (%s%%)",round(value/10^9,2),
                                  round(share,2)*100)),
                color="red",hjust="left")+ 
      geom_text(data=stormPCDamage[evtype_pcdmg=="flood"],
                aes(label=sprintf("%s bn$ (%s%%)",round(value/10^9,2),
                                  round(share,2)*100)),
                color="white",hjust="right")+
      facet_wrap(.~variable,scales = "free_x")
```



